services:
  - type: web
    name: ai-image-classifier-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 5000
